---
- name: Provisioner
  hosts: all
  become: true
  roles:
   - sou_podman

  post_tasks:
    - name: Ensure HaProxy is reachable
      loop:
        - grafana
        - prometheus
      when: inventory_hostname == "soufe1"
      ansible.builtin.uri:
        url: http://soufe1:8080/
        headers:
          host: "{{ item }}.lab.local"