---
- name: Ensure the data dir is present
  ansible.builtin.file:
    path: /containers_vols/haproxy
    state: directory
    mode: '0755'

- name: Ensure HaProxy configuration is present
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /containers_vols/haproxy/haproxy.cfg
    mode: u=rw,g=r,o=r

- name: Include certificate creation tasks
  ansible.builtin.include_tasks:
    file: certificates.yaml

- name: Ensure HaProxy hosts is present
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: u=rw,g=r,o=r

- name: Ensure HaProxy pod is present
  containers.podman.podman_container:
    name: haproxy
    image: docker.io/haproxy:3.1.2
    user: "{{ haproxy.user_id }}"
    volume:
      - /containers_vols/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:z
      - "{{ haproxy.ssl.certificate_path }}:/usr/local/etc/haproxy/certs/certificate.pem:z"
      - "{{ haproxy.ssl.private_key_path }}:/usr/local/etc/haproxy/certs/certificate.pem.key:z"
    expose:
      - 8080
      - 8443
    ports:
      - "8080:8080"
      - "8443:8443"