---
- name: Ensure the latest version of podman is present
  ansible.builtin.dnf:
    name: podman
    state: latest

- name: Include haproxy tasks
  when: inventory_hostname == "soufe1"
  ansible.builtin.include_tasks:
    file: haproxy.yaml

- name: Include prometheus tasks
  when: inventory_hostname == "soube2"
  ansible.builtin.include_tasks:
    file: prometheus.yaml

- name: Include grafana tasks
  when: inventory_hostname == "soube2"
  ansible.builtin.include_tasks:
    file: grafana.yaml
