---
- name: Ensure prometheus data dir is present
  when: inventory_hostname == "soube2"
  loop:
   - data
   - config
  ansible.builtin.file:
    path: "/containers_vols/prometheus/{{ item }}"
    state: directory
    owner: "{{ prometheus.user_id }}"
    group: "{{ prometheus.user_id }}"
    mode: '0755'

- name: Ensure Prometheus configuration is present
  when: inventory_hostname == "soube2"
  ansible.builtin.template:
    src: prometheus.yaml.j2
    owner: "{{ prometheus.user_id }}"
    group: "{{ prometheus.user_id }}"
    dest: /containers_vols/prometheus/config/prometheus.yaml
    mode: u=rw,g=r,o=r

- name: Ensure Prometheus pod is present
  when: inventory_hostname == "soube2"
  containers.podman.podman_container:
    name: prometheus
    user: "{{ prometheus.user_id }}"
    image: docker.io/prom/prometheus:v3.1.0
    volume:
      - /containers_vols/prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yml:z
      - /containers_vols/prometheus/data:/prometheus:z
    expose:
      - 9090
    ports:
      - "9090:9090"